# Site settings
title: login.gov
description: Welcome to the Login.gov developer documentation!
uswds: "/assets/uswds"

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Pages
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: main
