# Site settings
title: Login.gov Developer Docs
description: Welcome to the Login.gov developer documentation!
baseurl: '/identity-dev-docs'
uswds: "/assets/uswds"

# Pages
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: main
