# Site settings
title: login.gov docs
description: >
  Write an awesome description here.
baseurl: '/identity-dev-docs'
url: 'https://pages.18f.gov'

# Build settings
markdown: kramdown
sass:
  style: compressed